import = [
    "~/.config/alacritty/carbonfox.toml",
]

[window]
# decorations = "buttonless"
resize_increments = true

[window.padding]
x = 8
y = 8

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16.0
offset = { x = 0, y = 6 }

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"

