[shell]
program = "/usr/bin/env"
args = ["zsh", "-l", "-c", "exec sesh picker -itzHd"]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "Lilex Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Lilex Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Lilex Nerd Font Mono"
style = "Italic"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 0.95

[scrolling]
history = 10000
