import = [
    "~/.config/alacritty/carbonfox.toml",
]

[window]
# decorations = "Buttonless"
dynamic_title = false
title = "Terminal"
#opacity = 0.9
#startup_mode = "Maximized"
resize_increments = true

[window.padding]
x = 2
y = 2

[scrolling]
# history = 10000
# multiplier = 3

[font]
size = 16.0
offset = { x = 0, y = 6 }

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"
