[dotfiles]
"~/.config/aerospace" = { source = "config/aerospace", mode = "symlink-each" }
"~/.config/borders"   = { source = "config/borders", mode = "symlink-each" }
"~/.config/karabiner" = { source = "config/karabiner", mode = "symlink-each" }
