-- Basalt — Neovim colorscheme
-- Generated by basalt theme generator
-- https://github.com/julienmontagut/basalt

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "basalt"
vim.o.background = vim.env.THEME_VARIANT == "light" and "light" or "dark"
vim.o.termguicolors = true

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Use transparent background when terminal and neovim share the same theme
local bg = "#0e0e0e"
if vim.env.THEME == "basalt" then
  bg = "NONE"
end

-- Terminal colors
vim.g.terminal_color_0  = "#000000"
vim.g.terminal_color_1  = "#d47080"
vim.g.terminal_color_2  = "#5eb88a"
vim.g.terminal_color_3  = "#d4a656"
vim.g.terminal_color_4  = "#7ca2d8"
vim.g.terminal_color_5  = "#ae86d2"
vim.g.terminal_color_6  = "#5ca8aa"
vim.g.terminal_color_7  = "#cccccc"
vim.g.terminal_color_8  = "#3e3e44"
vim.g.terminal_color_9  = "#e2949e"
vim.g.terminal_color_10 = "#84cca6"
vim.g.terminal_color_11 = "#e4c080"
vim.g.terminal_color_12 = "#9cb8e4"
vim.g.terminal_color_13 = "#c4a2e0"
vim.g.terminal_color_14 = "#80beba"
vim.g.terminal_color_15 = "#ffffff"

-- Editor UI
hi("Normal", { fg = "#e7e5e5", bg = bg })
hi("NormalFloat", { fg = "#e7e5e5", bg = "#191a1a" })
hi("NormalNC", { fg = "#e7e5e5", bg = bg })
hi("FloatBorder", { fg = "#3e3e44", bg = "#191a1a" })
hi("FloatTitle", { fg = "#96b4e0", bg = "#191a1a", bold = true })
hi("WinSeparator", { fg = "#3e3e44" })
hi("VertSplit", { link = "WinSeparator" })
hi("Cursor", { fg = "#0e0e0e", bg = "#e7e5e5" })
hi("CursorLine", { bg = "#1f2020" })
hi("CursorColumn", { link = "CursorLine" })
hi("ColorColumn", { bg = "#141414" })
hi("LineNr", { fg = "#3e3e44" })
hi("CursorLineNr", { fg = "#acabaa", bold = true })
hi("SignColumn", { fg = "#3e3e44", bg = bg })
hi("FoldColumn", { fg = "#3e3e44", bg = bg })
hi("Folded", { fg = "#acabaa", bg = "#141414" })
hi("StatusLine", { fg = "#acabaa", bg = "#191a1a" })
hi("StatusLineNC", { fg = "#767575", bg = "#141414" })
hi("TabLine", { fg = "#acabaa", bg = "#141414" })
hi("TabLineFill", { bg = "#141414" })
hi("TabLineSel", { fg = "#e7e5e5", bg = "#1f2020", bold = true })
hi("WinBar", { fg = "#acabaa", bg = bg })
hi("WinBarNC", { fg = "#767575", bg = bg })
hi("Pmenu", { fg = "#e7e5e5", bg = "#191a1a" })
hi("PmenuSel", { fg = "#e7e5e5", bg = "#252626", bold = true })
hi("PmenuSbar", { bg = "#1f2020" })
hi("PmenuThumb", { bg = "#767575" })
hi("Visual", { bg = "#252626" })
hi("VisualNOS", { bg = "#252626" })
hi("Search", { fg = "#0e0e0e", bg = "#d4a656" })
hi("IncSearch", { fg = "#0e0e0e", bg = "#96b4e0" })
hi("CurSearch", { fg = "#0e0e0e", bg = "#96b4e0" })
hi("Substitute", { fg = "#0e0e0e", bg = "#d4a656" })
hi("MatchParen", { fg = "#96b4e0", bg = "#2b2c2c", bold = true })
hi("NonText", { fg = "#3e3e44" })
hi("SpecialKey", { fg = "#3e3e44" })
hi("Whitespace", { fg = "#3e3e44" })
hi("EndOfBuffer", { fg = "#3e3e44" })
hi("Directory", { fg = "#96b4e0" })
hi("Title", { fg = "#96b4e0", bold = true })
hi("Question", { fg = "#96b4e0" })
hi("MoreMsg", { fg = "#5eb88a" })
hi("ModeMsg", { fg = "#acabaa", bold = true })
hi("ErrorMsg", { fg = "#ee7d77" })
hi("WarningMsg", { fg = "#d4a656" })
hi("WildMenu", { link = "PmenuSel" })
hi("QuickFixLine", { bg = "#1f2020" })
hi("qfFileName", { fg = "#96b4e0" })
hi("qfLineNr", { fg = "#767575" })

-- Syntax
hi("Comment", { fg = "#767575", italic = true })
hi("Constant", { fg = "#5ca8aa" })
hi("String", { fg = "#5eb88a" })
hi("Character", { fg = "#5eb88a" })
hi("Number", { fg = "#d4a656" })
hi("Boolean", { fg = "#d4a656" })
hi("Float", { fg = "#d4a656" })
hi("Identifier", { fg = "#e7e5e5" })
hi("Function", { fg = "#96b4e0" })
hi("Statement", { fg = "#9a80cc" })
hi("Conditional", { fg = "#9a80cc" })
hi("Repeat", { fg = "#9a80cc" })
hi("Label", { fg = "#9a80cc" })
hi("Operator", { fg = "#acabaa" })
hi("Keyword", { fg = "#9a80cc" })
hi("Exception", { fg = "#9a80cc" })
hi("PreProc", { fg = "#7ca2d8" })
hi("Include", { fg = "#7ca2d8" })
hi("Define", { fg = "#7ca2d8" })
hi("Macro", { fg = "#7ca2d8" })
hi("PreCondit", { fg = "#7ca2d8" })
hi("Type", { fg = "#5ca8aa" })
hi("StorageClass", { fg = "#9a80cc" })
hi("Structure", { fg = "#5ca8aa" })
hi("Typedef", { fg = "#5ca8aa" })
hi("Special", { fg = "#ae86d2" })
hi("SpecialChar", { fg = "#ae86d2" })
hi("Tag", { fg = "#96b4e0" })
hi("Delimiter", { fg = "#acabaa" })
hi("SpecialComment", { fg = "#767575", bold = true })
hi("Debug", { fg = "#d47080" })
hi("Underlined", { fg = "#96b4e0", underline = true })
hi("Ignore", { fg = "#3e3e44" })
hi("Error", { fg = "#ee7d77", bold = true })
hi("Todo", { fg = "#b7e981", bold = true })

-- Treesitter
hi("@variable", { fg = "#e7e5e5" })
hi("@variable.builtin", { fg = "#d47080" })
hi("@variable.parameter", { fg = "#acabaa", italic = true })
hi("@variable.member", { fg = "#e7e5e5" })
hi("@constant", { fg = "#5ca8aa" })
hi("@constant.builtin", { fg = "#d4a656" })
hi("@constant.macro", { fg = "#5ca8aa" })
hi("@module", { fg = "#acabaa" })
hi("@label", { fg = "#9a80cc" })
hi("@string", { fg = "#5eb88a" })
hi("@string.escape", { fg = "#ae86d2" })
hi("@string.regexp", { fg = "#ae86d2" })
hi("@string.special", { fg = "#ae86d2" })
hi("@character", { fg = "#5eb88a" })
hi("@number", { fg = "#d4a656" })
hi("@boolean", { fg = "#d4a656" })
hi("@float", { fg = "#d4a656" })
hi("@function", { fg = "#96b4e0" })
hi("@function.builtin", { fg = "#7ca2d8" })
hi("@function.call", { fg = "#96b4e0" })
hi("@function.macro", { fg = "#7ca2d8" })
hi("@function.method", { fg = "#96b4e0" })
hi("@function.method.call", { fg = "#96b4e0" })
hi("@constructor", { fg = "#5ca8aa" })
hi("@operator", { fg = "#acabaa" })
hi("@keyword", { fg = "#9a80cc" })
hi("@keyword.coroutine", { fg = "#9a80cc" })
hi("@keyword.function", { fg = "#9a80cc" })
hi("@keyword.operator", { fg = "#8468b8" })
hi("@keyword.import", { fg = "#7ca2d8" })
hi("@keyword.storage", { fg = "#9a80cc" })
hi("@keyword.repeat", { fg = "#9a80cc" })
hi("@keyword.return", { fg = "#9a80cc" })
hi("@keyword.conditional", { fg = "#9a80cc" })
hi("@keyword.exception", { fg = "#9a80cc" })
hi("@type", { fg = "#5ca8aa" })
hi("@type.builtin", { fg = "#5ca8aa", italic = true })
hi("@type.qualifier", { fg = "#9a80cc" })
hi("@attribute", { fg = "#7ca2d8" })
hi("@property", { fg = "#e7e5e5" })
hi("@punctuation.bracket", { fg = "#acabaa" })
hi("@punctuation.delimiter", { fg = "#acabaa" })
hi("@punctuation.special", { fg = "#ae86d2" })
hi("@comment", { fg = "#767575", italic = true })
hi("@comment.todo", { fg = "#b7e981", bold = true })
hi("@comment.note", { fg = "#96b4e0", bold = true })
hi("@comment.warning", { fg = "#d4a656", bold = true })
hi("@comment.error", { fg = "#ee7d77", bold = true })
hi("@tag", { fg = "#96b4e0" })
hi("@tag.attribute", { fg = "#9a80cc" })
hi("@tag.delimiter", { fg = "#acabaa" })
hi("@markup.heading", { fg = "#96b4e0", bold = true })
hi("@markup.bold", { bold = true })
hi("@markup.italic", { italic = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.underline", { underline = true })
hi("@markup.link", { fg = "#96b4e0", underline = true })
hi("@markup.link.url", { fg = "#7ca2d8", underline = true })
hi("@markup.raw", { fg = "#5eb88a" })
hi("@markup.list", { fg = "#acabaa" })

-- LSP Semantic Tokens
hi("@lsp.type.namespace", { link = "@module" })
hi("@lsp.type.type", { link = "@type" })
hi("@lsp.type.class", { link = "@type" })
hi("@lsp.type.enum", { link = "@type" })
hi("@lsp.type.interface", { link = "@type" })
hi("@lsp.type.struct", { link = "@type" })
hi("@lsp.type.parameter", { link = "@variable.parameter" })
hi("@lsp.type.variable", { link = "@variable" })
hi("@lsp.type.property", { link = "@property" })
hi("@lsp.type.function", { link = "@function" })
hi("@lsp.type.method", { link = "@function.method" })
hi("@lsp.type.macro", { link = "@function.macro" })
hi("@lsp.type.decorator", { link = "@attribute" })
hi("@lsp.mod.deprecated", { strikethrough = true })

-- Diagnostics
hi("DiagnosticError", { fg = "#ee7d77" })
hi("DiagnosticWarn", { fg = "#d4a656" })
hi("DiagnosticInfo", { fg = "#96b4e0" })
hi("DiagnosticHint", { fg = "#5ca8aa" })
hi("DiagnosticOk", { fg = "#5eb88a" })
hi("DiagnosticUnderlineError", { undercurl = true, sp = "#ee7d77" })
hi("DiagnosticUnderlineWarn", { undercurl = true, sp = "#d4a656" })
hi("DiagnosticUnderlineInfo", { undercurl = true, sp = "#96b4e0" })
hi("DiagnosticUnderlineHint", { undercurl = true, sp = "#5ca8aa" })
hi("DiagnosticVirtualTextError", { fg = "#bb5551", bg = "#7f2927" })
hi("DiagnosticVirtualTextWarn", { fg = "#d4a656", bg = "#141414" })
hi("DiagnosticVirtualTextInfo", { fg = "#7ca2d8", bg = "#141414" })
hi("DiagnosticVirtualTextHint", { fg = "#5ca8aa", bg = "#141414" })

-- Diff
hi("DiffAdd", { fg = "#5eb88a", bg = "#141414" })
hi("DiffChange", { fg = "#d4a656", bg = "#141414" })
hi("DiffDelete", { fg = "#d47080", bg = "#141414" })
hi("DiffText", { fg = "#d4a656", bg = "#1f2020" })
hi("Added", { fg = "#5eb88a" })
hi("Changed", { fg = "#d4a656" })
hi("Removed", { fg = "#d47080" })

-- Git Signs
hi("GitSignsAdd", { fg = "#5eb88a" })
hi("GitSignsChange", { fg = "#d4a656" })
hi("GitSignsDelete", { fg = "#d47080" })
hi("GitSignsCurrentLineBlame", { fg = "#767575" })

-- Telescope
hi("TelescopeNormal", { fg = "#e7e5e5", bg = "#191a1a" })
hi("TelescopeBorder", { fg = "#3e3e44", bg = "#191a1a" })
hi("TelescopeTitle", { fg = "#96b4e0", bold = true })
hi("TelescopePromptNormal", { fg = "#e7e5e5", bg = "#1f2020" })
hi("TelescopePromptBorder", { fg = "#3e3e44", bg = "#1f2020" })
hi("TelescopePromptTitle", { fg = "#96b4e0", bg = "#1f2020", bold = true })
hi("TelescopePromptPrefix", { fg = "#96b4e0" })
hi("TelescopeSelection", { fg = "#e7e5e5", bg = "#252626", bold = true })
hi("TelescopeMatching", { fg = "#96b4e0", bold = true })
hi("TelescopeResultsNormal", { fg = "#acabaa" })
hi("TelescopePreviewNormal", { fg = "#e7e5e5", bg = "#141414" })
hi("TelescopePreviewBorder", { fg = "#3e3e44", bg = "#141414" })
hi("TelescopePreviewTitle", { fg = "#96b4e0", bg = "#141414", bold = true })

-- Indent Blankline
hi("IblIndent", { fg = "#3e3e44" })
hi("IblScope", { fg = "#767575" })

-- Lazy.nvim
hi("LazyButton", { fg = "#acabaa", bg = "#141414" })
hi("LazyButtonActive", { fg = "#e7e5e5", bg = "#252626", bold = true })
hi("LazyH1", { fg = "#0e0e0e", bg = "#96b4e0", bold = true })
hi("LazySpecial", { fg = "#9a80cc" })

-- Which-key
hi("WhichKey", { fg = "#96b4e0" })
hi("WhichKeyGroup", { fg = "#9a80cc" })
hi("WhichKeyDesc", { fg = "#acabaa" })
hi("WhichKeySeparator", { fg = "#3e3e44" })
hi("WhichKeyFloat", { bg = "#191a1a" })
hi("WhichKeyBorder", { fg = "#3e3e44", bg = "#191a1a" })
hi("WhichKeyValue", { fg = "#acabaa" })

-- Notify
hi("NotifyERRORBorder", { fg = "#bb5551" })
hi("NotifyERRORIcon", { fg = "#ee7d77" })
hi("NotifyERRORTitle", { fg = "#ee7d77", bold = true })
hi("NotifyWARNBorder", { fg = "#d4a656" })
hi("NotifyWARNIcon", { fg = "#d4a656" })
hi("NotifyWARNTitle", { fg = "#d4a656", bold = true })
hi("NotifyINFOBorder", { fg = "#7ca2d8" })
hi("NotifyINFOIcon", { fg = "#96b4e0" })
hi("NotifyINFOTitle", { fg = "#96b4e0", bold = true })

-- Neo-tree
hi("NeoTreeNormal", { fg = "#acabaa", bg = "#141414" })
hi("NeoTreeNormalNC", { fg = "#acabaa", bg = "#141414" })
hi("NeoTreeDirectoryIcon", { fg = "#7ca2d8" })
hi("NeoTreeDirectoryName", { fg = "#96b4e0" })
hi("NeoTreeFileName", { fg = "#acabaa" })
hi("NeoTreeGitAdded", { fg = "#5eb88a" })
hi("NeoTreeGitModified", { fg = "#d4a656" })
hi("NeoTreeGitDeleted", { fg = "#d47080" })
hi("NeoTreeGitConflict", { fg = "#d47080", bold = true })
hi("NeoTreeIndentMarker", { fg = "#3e3e44" })
hi("NeoTreeRootName", { fg = "#96b4e0", bold = true })
