[manager]
ratio = [ 1, 2, 2]
show_hidden = true

# [opener]
# edit = [
# 	{ run = 'nvim "$@"', block = true },
# ]
# open = [
# 	{ run = 'xdg-open "$@"', desc = "Open", for = "macos" },
# ]

# [open]
# prepend_rules = [
# 	{ name = "*.json", use = "edit" },
# 	{ name = "*.html", use = [ "open", "edit" ] },
# ]
# append_rules = [
# 	{ name = "*", use = "my-fallback" },
# ]
