[colors]
ansi = [
    "#000000",
    "#f38ba8",
    "#a6e3a1",
    "#f9e2af",
    "#89b4fa",
    "#cba6f7",
    "#89dceb",
    "#cccccc",
]
background = "#0e0e0e"
brights = [
    "#45475a",
    "#f38ba8",
    "#a6e3a1",
    "#f9e2af",
    "#89b4fa",
    "#cba6f7",
    "#89dceb",
    "#ffffff",
]
cursor_bg = "#e7e5e5"
cursor_border = "#e7e5e5"
cursor_fg = "#0e0e0e"
foreground = "#e7e5e5"
selection_bg = "#252626"
selection_fg = "#e7e5e5"

[colors.indexed]
16 = "#aec6ff"
17 = "#ae8de9"

[metadata]
name = "Sweet Neutral Dark"
