[settings]
experimental = true
lockfile = true

[settings.github]
use_git_credentials = true

[tools]

# Languages installed by default
rust = { version = "latest", components = "rust-analyzer,rust-src" }
dotnet = "latest"

# CLI tools 
bat = "latest"
claude-code = "latest"
delta = "latest"
dua = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
jj = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
mprocs = "latest"
neovim = "latest"
ripgrep = "latest"
scaleway = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
xh = "latest"
zoxide = "latest"
zellij = "latest"

# CLI tools out of the registry
"cargo:bacon" = "latest"
"aqua:maaslalani/slides" = "latest"
bitwarden = "latest"
