[settings]
experimental = true
lockfile = true

[settings.github]
use_git_credentials = true

[tools]
lua = "latest"
rust = "latest"
dotnet = "latest"

claude-code = "latest"

# kubernetes
helm = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
kubectx = "latest"

# LSPs / formatters
lua-language-server = "latest"
stylua = "latest"
shfmt = "latest"
taplo = "latest"
rust-analyzer = "latest"
helm-ls = "latest"
"npm:yaml-language-server" = "latest"
"npm:bash-language-server" = "latest"
zellij = "latest"

# CLI tools 
bat = "latest"
delta = "latest"
dua = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
jj = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
mprocs = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
xh = "latest"
zoxide = "latest"

# CLI tools not in the registry 
"cargo:bacon" = "latest"
"cargo:nickel-lang-cli" = "latest"
opentofu = "latest"
scaleway-cli = "latest"
"aqua:maaslalani/slides" = "latest"
